/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as ProductsCustomRouteImport } from './routes/products.custom'
import { Route as ProductsAgentRouteImport } from './routes/products.agent'
import { Route as ProductsAcademyRouteImport } from './routes/products.academy'
import { Route as CaseStudiesSwissmemRouteImport } from './routes/case-studies.swissmem'
import { Route as CaseStudiesSwissBankRouteImport } from './routes/case-studies.swiss-bank'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const ProductsCustomRoute = ProductsCustomRouteImport.update({
  id: '/products/custom',
  path: '/products/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAgentRoute = ProductsAgentRouteImport.update({
  id: '/products/agent',
  path: '/products/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAcademyRoute = ProductsAcademyRouteImport.update({
  id: '/products/academy',
  path: '/products/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSwissmemRoute = CaseStudiesSwissmemRouteImport.update({
  id: '/swissmem',
  path: '/swissmem',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesSwissBankRoute = CaseStudiesSwissBankRouteImport.update({
  id: '/swiss-bank',
  path: '/swiss-bank',
  getParentRoute: () => CaseStudiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/letter': typeof LetterRoute
  '/solutions': typeof SolutionsRoute
  '/case-studies/swiss-bank': typeof CaseStudiesSwissBankRoute
  '/case-studies/swissmem': typeof CaseStudiesSwissmemRoute
  '/products/academy': typeof ProductsAcademyRoute
  '/products/agent': typeof ProductsAgentRoute
  '/products/custom': typeof ProductsCustomRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/letter': typeof LetterRoute
  '/solutions': typeof SolutionsRoute
  '/case-studies/swiss-bank': typeof CaseStudiesSwissBankRoute
  '/case-studies/swissmem': typeof CaseStudiesSwissmemRoute
  '/products/academy': typeof ProductsAcademyRoute
  '/products/agent': typeof ProductsAgentRoute
  '/products/custom': typeof ProductsCustomRoute
  '/case-studies': typeof CaseStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/letter': typeof LetterRoute
  '/solutions': typeof SolutionsRoute
  '/case-studies/swiss-bank': typeof CaseStudiesSwissBankRoute
  '/case-studies/swissmem': typeof CaseStudiesSwissmemRoute
  '/products/academy': typeof ProductsAcademyRoute
  '/products/agent': typeof ProductsAgentRoute
  '/products/custom': typeof ProductsCustomRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/letter'
    | '/solutions'
    | '/case-studies/swiss-bank'
    | '/case-studies/swissmem'
    | '/products/academy'
    | '/products/agent'
    | '/products/custom'
    | '/case-studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/letter'
    | '/solutions'
    | '/case-studies/swiss-bank'
    | '/case-studies/swissmem'
    | '/products/academy'
    | '/products/agent'
    | '/products/custom'
    | '/case-studies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/letter'
    | '/solutions'
    | '/case-studies/swiss-bank'
    | '/case-studies/swissmem'
    | '/products/academy'
    | '/products/agent'
    | '/products/custom'
    | '/case-studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  LetterRoute: typeof LetterRoute
  SolutionsRoute: typeof SolutionsRoute
  ProductsAcademyRoute: typeof ProductsAcademyRoute
  ProductsAgentRoute: typeof ProductsAgentRoute
  ProductsCustomRoute: typeof ProductsCustomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/products/custom': {
      id: '/products/custom'
      path: '/products/custom'
      fullPath: '/products/custom'
      preLoaderRoute: typeof ProductsCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/agent': {
      id: '/products/agent'
      path: '/products/agent'
      fullPath: '/products/agent'
      preLoaderRoute: typeof ProductsAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/academy': {
      id: '/products/academy'
      path: '/products/academy'
      fullPath: '/products/academy'
      preLoaderRoute: typeof ProductsAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/swissmem': {
      id: '/case-studies/swissmem'
      path: '/swissmem'
      fullPath: '/case-studies/swissmem'
      preLoaderRoute: typeof CaseStudiesSwissmemRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/swiss-bank': {
      id: '/case-studies/swiss-bank'
      path: '/swiss-bank'
      fullPath: '/case-studies/swiss-bank'
      preLoaderRoute: typeof CaseStudiesSwissBankRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesSwissBankRoute: typeof CaseStudiesSwissBankRoute
  CaseStudiesSwissmemRoute: typeof CaseStudiesSwissmemRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSwissBankRoute: CaseStudiesSwissBankRoute,
  CaseStudiesSwissmemRoute: CaseStudiesSwissmemRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  LetterRoute: LetterRoute,
  SolutionsRoute: SolutionsRoute,
  ProductsAcademyRoute: ProductsAcademyRoute,
  ProductsAgentRoute: ProductsAgentRoute,
  ProductsCustomRoute: ProductsCustomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
